"""Asynchronous FIFO processing for unknown object crops.

This module keeps slow VLM inference out of the real-time semantic image path.
The semantic adapter can immediately publish an ``unknown_object`` label to
Hydra, enqueue the crop here, and continue mapping. A background thread later
calls the VLM and publishes a delayed semantic/risk update keyed by the
``adapter_object_id``.

The design deliberately separates two concepts:

``semantic_label_id``
    A stable class label written into the Hydra semantic image, for example
    ``unknown_object`` or ``object_candidate``.

``adapter_object_id``
    A per-observation identifier used to associate delayed VLM results with the
    SAM/RAP observation and, later, with a Hydra object node in a fusion layer.
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from queue import Empty, Full, Queue
from threading import Event, Lock, Thread
from typing import Any, Callable, Dict, List, Optional, Set
import time

import numpy as np


@dataclass
class UnknownObjectJob:
    """A single unknown-object crop waiting for VLM inference.

    Parameters
    ----------
    adapter_object_id:
        Stable ID generated by the semantic adapter for this object observation.
        The VLM result is published with the same ID.
    stamp:
        ROS-style timestamp dictionary: ``{"sec": int, "nanosec": int}``.
    frame_id:
        Camera frame in which the crop was observed.
    crop_rgb:
        RGB crop as a NumPy array. This remains in memory and is not published
        unless a caller explicitly chooses to do so elsewhere.
    bbox_xywh:
        2D bounding box in full-image coordinates.
    centroid_camera:
        Optional 3D centroid in the camera frame.
    centroid_map:
        Optional 3D centroid in the map frame.
    semantic_label:
        Immediate label sent to Hydra, usually ``unknown_object``.
    semantic_label_id:
        Integer class ID written into the Hydra semantic image.
    rap_label / rap_confidence:
        The RAP result that caused this object to be considered unknown.
    mask_area_px:
        Number of pixels in the SAM mask after filtering.
    """

    adapter_object_id: str
    stamp: Dict[str, int]
    frame_id: str
    crop_rgb: np.ndarray
    bbox_xywh: List[int]
    centroid_camera: Optional[List[float]]
    centroid_map: Optional[List[float]]
    semantic_label: str
    semantic_label_id: int
    rap_label: str
    rap_confidence: float
    mask_area_px: int

    def metadata(self) -> Dict[str, Any]:
        """Return JSON-serializable metadata without the image crop."""
        data = asdict(self)
        data.pop("crop_rgb", None)
        return data


class UnknownObjectVlmQueue:
    """Bounded FIFO queue with one background VLM worker.

    The queue is intentionally small and bounded. If unknown objects are
    produced faster than the VLM can process them, the configured drop policy is
    applied instead of allowing unbounded memory growth.
    """

    def __init__(
        self,
        vlm_client: Any,
        publish_callback: Callable[[Dict[str, Any]], None],
        *,
        enabled: bool = True,
        max_size: int = 32,
        drop_policy: str = "drop_oldest",
        logger: Optional[Any] = None,
    ) -> None:
        self.vlm_client = vlm_client
        self.publish_callback = publish_callback
        self.enabled = bool(enabled)
        self.max_size = int(max_size)
        self.drop_policy = str(drop_policy)
        self.logger = logger

        self._queue: Queue[UnknownObjectJob] = Queue(maxsize=self.max_size)
        self._stop_event = Event()
        self._thread: Optional[Thread] = None
        self._lock = Lock()
        self._queued_or_processed_ids: Set[str] = set()

    def start(self) -> None:
        """Start the background VLM worker thread."""
        if not self.enabled:
            return
        if self._thread is not None and self._thread.is_alive():
            return
        self._thread = Thread(target=self._worker_loop, daemon=True)
        self._thread.start()
        self._log_info("Unknown-object VLM FIFO worker started.")

    def stop(self, timeout: float = 2.0) -> None:
        """Request worker shutdown and wait briefly."""
        self._stop_event.set()
        if self._thread is not None:
            self._thread.join(timeout=timeout)

    def size(self) -> int:
        """Current number of queued jobs."""
        return self._queue.qsize()

    def enqueue(self, job: UnknownObjectJob) -> bool:
        """Push an unknown object into the FIFO queue.

        Returns ``True`` when the job is queued. Returns ``False`` if the queue
        is disabled, the job is duplicate, or the drop policy rejects it.
        """
        if not self.enabled:
            return False

        with self._lock:
            if job.adapter_object_id in self._queued_or_processed_ids:
                return False
            self._queued_or_processed_ids.add(job.adapter_object_id)

        try:
            self._queue.put_nowait(job)
            return True
        except Full:
            if self.drop_policy == "drop_newest":
                self._log_warn(
                    f"VLM queue full; dropping newest object {job.adapter_object_id}."
                )
                return False

            # Default: keep the most recent observation by dropping the oldest.
            try:
                dropped = self._queue.get_nowait()
                self._log_warn(
                    f"VLM queue full; dropping oldest object {dropped.adapter_object_id}."
                )
            except Empty:
                pass

            try:
                self._queue.put_nowait(job)
                return True
            except Full:
                return False

    def _worker_loop(self) -> None:
        while not self._stop_event.is_set():
            try:
                job = self._queue.get(timeout=0.1)
            except Empty:
                continue

            started = time.perf_counter()
            update: Dict[str, Any]
            try:
                context = (
                    "Unknown object crop from RGB-D semantic adapter. "
                    f"adapter_object_id={job.adapter_object_id}; "
                    f"RAP={job.rap_label}:{job.rap_confidence:.3f}; "
                    f"bbox_xywh={job.bbox_xywh}; "
                    f"centroid_map={job.centroid_map}"
                )
                result = self.vlm_client.query(job.crop_rgb, context=context)
                latency = time.perf_counter() - started

                update = {
                    "adapter_object_id": job.adapter_object_id,
                    "stamp": job.stamp,
                    "frame_id": job.frame_id,
                    "semantic_label": job.semantic_label,
                    "semantic_label_id": job.semantic_label_id,
                    "bbox_xywh": job.bbox_xywh,
                    "centroid_camera": job.centroid_camera,
                    "centroid_map": job.centroid_map,
                    "rap_label": job.rap_label,
                    "rap_confidence": float(job.rap_confidence),
                    "vlm_label": result.label,
                    "vlm_confidence": float(result.confidence),
                    "risk_type": result.risk_type,
                    "risk_score": float(result.risk_score),
                    "reason": result.reason,
                    "source": result.source,
                    "vlm_latency_s": float(latency),
                    "queue_size_after_pop": self.size(),
                }
            except Exception as exc:  # defensive: VLM failures must not kill worker
                latency = time.perf_counter() - started
                update = {
                    "adapter_object_id": job.adapter_object_id,
                    "stamp": job.stamp,
                    "frame_id": job.frame_id,
                    "semantic_label": job.semantic_label,
                    "semantic_label_id": job.semantic_label_id,
                    "bbox_xywh": job.bbox_xywh,
                    "centroid_camera": job.centroid_camera,
                    "centroid_map": job.centroid_map,
                    "rap_label": job.rap_label,
                    "rap_confidence": float(job.rap_confidence),
                    "vlm_label": "unknown_object",
                    "vlm_confidence": 0.0,
                    "risk_type": "unknown",
                    "risk_score": 0.0,
                    "reason": f"VLM worker failed: {exc}",
                    "source": "vlm_worker_failed",
                    "vlm_latency_s": float(latency),
                    "queue_size_after_pop": self.size(),
                }

            self.publish_callback(update)
            self._queue.task_done()

    def _log_info(self, msg: str) -> None:
        if self.logger is not None:
            self.logger.info(msg)

    def _log_warn(self, msg: str) -> None:
        if self.logger is not None:
            self.logger.warn(msg)
