<?xml version="1.0"?>
<package format="3">
  <name>rsg_dsg_visualizer</name>
  <version>0.1.0</version>
  <description>Wrapper and monitor package for visualizing Hydra frontend/backend DSG updates in RViz.</description>

  <maintainer email="fabin@example.com">Fabin</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>hydra_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>hydra_visualizer</exec_depend>
  <exec_depend>hydra_ros</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
